### PR TITLE
#610 - DataTable with Scrollbar: Sorting decreases the width

### PR DESCRIPTION
**Pull request by FrankHossfeld**
Fix for #610.

Testet with macOS (Safari, Chrome, FireFox)

Needs more testing on other plattforms!

### CODE REVIEW

**Comment by vegegoku** [comment]
removing those 2 pixels will reproduce the old bug of miss-aligned column headers with vertical scrollbar.

**Comment by FrankHossfeld** [comment]
Mmmh, let me check ...

**Comment by vegegoku** [comment]
You will need to have a fixed table with vertical scrollbar and bordered style

**Comment by FrankHossfeld** [comment]
Ok, got it, then the bordered style is the problem ... will check it and come back to you.

**Comment by FrankHossfeld** [comment]
Mmmmh, I think I miss something ... 


https://user-images.githubusercontent.com/8287845/144119307-849694f3-c9de-4d40-8cb7-5d1e0c3af985.mov

**Comment by vegegoku** [comment]
Fixed in #610 
We need the the `-2 px` to avoid unnecessary horizontal scrollbars but we moved to a fix place where they wont be called every time sort is applied.
We also needed to count for screen size change when we calculate the scrollbars width.

**Pull request closed without merging**
