### PR TITLE
Enhance the TimeBox with a possibility to set also seconds.

### PR DESCRIPTION
**Pull request by HMIDeer**
Fix for https://github.com/DominoKit/domino-ui/issues/379

### CODE REVIEW

**Comment by HMIDeer** [comment]
I am not really lucky with the duplicated code in Clock12 and Clock24. Will restructure it if this is ok for you!?

**Comment by vegegoku** [comment]
I need some time to test it locally.

**Comment by vegegoku** [comment]
I tested locally in the demo site and this isn't working after you switch to the seconds it still changing the minutes instead. unless I am missing something here.

**Comment by HMIDeer** [comment]
> 
> 
> I tested locally in the demo site and this isn't working after you switch to the seconds it still changing the minutes instead. unless I am missing something here.

You are right, i've fixed it. :-)

**Comment by vegegoku** [comment]
I did another round of testing, there is just one more small thing, after selecting the minutes is should automatically switch to select seconds, this is what happens when selecting hours it automatically switches to minutes selection.
I think once this fix is applied we can merge this.

Thank you for the awesome work.

**Pull request merged**
