### PR TITLE
Implement FieldSet control

### PR DESCRIPTION
**Pull request by salashnik**
#149?

### CODE REVIEW

**Comment by salashnik** [comment]
It's like BlockHeader, but use `fieldset/legend` instead `div/h2` & `appendChild` adds elements into main control instead description

**Comment by vegegoku** [comment]
@salashnik i dont think an implementation based on BlockHeader is the right thing to do, actually i dont see a need to implement this component since it is easily doable with we already have

```
inputCard.appendChild(DominoElement.of(form())
                .appendChild(DominoElement.of(fieldset())
                        .appendChild(legend().textContent("Fields set"))
                        .appendChild(TextBox.create().setPlaceholder("Username"))
                        .appendChild(TextBox.password().setPlaceholder("Password"))
                )
        );
```
which produces something like this

selection_019

Would you like to elaborate more about your use case?
What makes the above example not enough for you?
Can you provide a screenshot of what you are trying to do?

**Comment by vegegoku** [comment]
@salashnik We need a form component that allows fields to fit correctly into other components like cards, also we need to keep in mind that a single form can have multiple fieldsets each with its own legend, this means once we have the fieldset component we can make it provide some useful methods .. like disable/enable all fields in that fieldset, show/hide the fieldset ... etc

the implementation above does not provide any of these functions, but also has methods came from BlockHeader that does not make sense for a field set like `invertLegend` method.

is it ok if you use the code snippet i sent until i finish the implementation of the Form component?

**Comment by salashnik** [comment]
> the implementation above does not provide any of these functions,

? if i hide fieldset this also hide all childs, i can change order of fieldsets etc...

> but also has methods came from BlockHeader that does not make sense for a field set like invertLegend method.

? works comletely like in blockheader- place description before header

> is it ok if you use the code snippet i sent until i finish the implementation of the Form component?

i can easy place my control in my project and use it without changes in domino-ui but...

**Pull request closed without merging**
