### PR TITLE
Window feature request

### PR DESCRIPTION
**Pull request by happyhua**
This is a feature request.

Hereby you can override click action on close icon. Overriding click action is different than overriding close method.

A use case is for example when you open the modal window with history state.

In main window, you click something to open the modal window,
```
window.open()
DomGlobal.history.pushState(a state to remember the window open action)
```
Now either clicking on close icon or clicking on history back button (or android back button) user may close the window.
```
protected void onClickClose(Event event) {
  DomGlobal.history.back();
  close(); // Optional code, absent if close action is handled by history state watcher. This is also the reason that close() cannot be overridden.
}
```
Of course additional code is needed in main window to remember the state if it should open or close the modal window.

### CODE REVIEW

**Comment by vegegoku** [comment]
Window is a modal dialog and you can add close/open listeners
```java
myWindow.addCloseListener(()-> {do what ever})

```
which is better than just overriding close button, since this can be also called when auto close is true.

**Comment by happyhua** [comment]
I have thought about it. It is not exactly the same, I will prepare a good use case example with history state. Probably tomorrow.

**Comment by happyhua** [comment]
```
// Example one, simple one with NO history state support.
Window window1 = new Window("Window");

window1.appendChild(Elements.div().textContent("child in window, " +
		"clicking on history back button or android back button will NOT close this window"));

Button button1 = new Button("Open Window");
button1.addClickListener(event -> window1.open());


// Example two, showing closed handler will not work.
Window window2 = new Window("Window with close handler");
window2.appendChild(Elements.div().textContent("child in window with close handler, " +
		"clicking on history back button or android back button will close this window"));

window2.addCloseListener(() -> {
	// Here we do not know if it is closed by clicking on close button or by history back button.

	// Without a close handler, the only scenario not caught is when user clicking on the close button.
	// The modal window is closed, but the history state is not back to the main state.

	// However, if history back is used here, it probably makes things worse, there could be a loop between close and popstate change.
	// DomGlobal.history.back();
});

Button button2 = new Button("Open window with close handler");
button2.addClickListener(event -> {
	window2.open();
	// Window is opened and we give it a history state. Now we may also close the window through history back button.
	DomGlobal.history.pushState("window2", "");
});

DomGlobal.window.addEventListener("popstate", event -> {
	if ("window2".equals(DomGlobal.history.state)) {
		// Open window2 again because the user clicking on history forward button, hence no need to pushState again.
		window2.open();
	} else {
		// Always close window2 since there are just two states in this simple application.
		// In a real application things can be complex.
		window2.close();
	}
});


// Example 3, showing on click overriding implements a correct interaction between main and modal window through history states change.
Window window3 = new Window("Window with on click overriding") {
	@Override
	protected void onClickClose(Event event) {
		// Here we simply call history back, let window popstate handling the close action.
		DomGlobal.history.back();
	}
};
window3.appendChild(Elements.div().textContent("child in window with on click overriding, " +
		"clicking on history back button or android back button will close this window"));

Button button3 = new Button("Open window with on click overriding");
button3.addClickListener(event -> {
	window3.open();
	// Window is opened with a history state. Now we may also close the window through history back button.
	DomGlobal.history.pushState("window3", "");
});

DomGlobal.window.addEventListener("popstate", event -> {
	if ("window3".equals(DomGlobal.history.state)) {
		// Open window3 again because the user clicking on history forward button, hence no need to pushState again.
		window3.open();
	} else {
		// Always close window3 since there are just two states in this simple application.
		// In a real application things can be complex.
		window3.close();
	}
});
```

**Comment by happyhua** [comment]
```
DomGlobal.document.body.appendChild(button1.element());
DomGlobal.document.body.appendChild(button2.element());
DomGlobal.document.body.appendChild(button3.element());
```

Yes, the above example almost works, except you need to attach the buttons to the html body.

As you can see, window2 without close handler almost works, but without updating the history state, so the overriding in window3 is required here.

**Comment by vegegoku** [comment]
Actually you dont need to override the close button, but you need to have the right check to make sure everything works as expected, here is an example : 
```java

        Window window = Window.create("Sample window")
                .setFixed()
                .appendChild(DominoElement.div().setTextContent("This window will close if you hit the back button"));

        window.addCloseListener(() -> {
            if(history.currentToken().endsWithPath("window")){
                history.back();
            }
        });

        history.listen(TokenFilter.endsWith("window"), state -> {
            window.open();
        });
        history.listen(NotTokenFilter.of(TokenFilter.endsWith("window")), state -> window.close());

        layout.getContentPanel()
                .appendChild(Card.create("test window with history")
                .appendChild(Button.create("open window")
                        .addClickListener(evt -> history.fireState("window"))
                ));
```

I am using DominoHistory here just because it make things easier to work with the history state, and the NoTokenFilter is a custom one
```java
public static class NotTokenFilter implements TokenFilter {

        private final TokenFilter tokenFilter;

        public static NotTokenFilter of(TokenFilter tokenFilter){
            return new NotTokenFilter(tokenFilter);
        }

        public NotTokenFilter(TokenFilter tokenFilter) {
            this.tokenFilter = tokenFilter;
        }

        @Override
        public boolean filter(HistoryToken historyToken) {
            return !tokenFilter.filter(historyToken);
        }

        @Override
        public NormalizedToken normalizeToken(String rootPath, String token) {
            return tokenFilter.normalizeToken(rootPath, token);
        }
    }
```

You can do the same without the DominoHistory if you want, but the idea is that the back will remove the token before calling the listeners so it should work with that check.

**Comment by happyhua** [comment]
I see your point and would like to try it. Are DominoHistory and TokenFilter included in other library than domino-ui? I cannot find them in domino-ui project.

No we can make sure that the window close handler is fired only after user clicking on close button due to the token check.

The flow seems to be:
User click on close icon -> window close is called -> window close handler is fired -> history back is called -> history listener sees a state change -> window close is called again.

This can be a loop, at least, window close is called twice. I think here you also need a check in history listener, like do not close window again if is already closed, right?

This approaching should also work. Compare to overriding solution, code becomes a little longer, since it needs two extra if statements. One if statement by window close handler, one if statement by history listener to prevent repeated close call.

Do I say things correctly?

**Comment by vegegoku** [comment]
[Domino-history ](https://github.com/DominoKit/domino-history) is another library in the dominokit family.

The problem with override solution is that the close have a lot of logic behind it, and if you want to override it then you will need to make sure to copy and alter that code or you will have to call the super, calling super will still call the change handlers.

the logic in the close include handling the adding and removing of window from the dom, handling multiple modals open at the same time, and handle proper positioning of the modals backdrop mask, and finally calls the close handlers.

I would if you want to implement the override solution there will a lot more code to write to make this work as intended.
the sample i provided above is a fully working example with history working correctly.

and the `Not` token filter will be included by default in next domino-history RC release.

**Comment by happyhua** [comment]
I will close this PR for now, maybe there are better solution for this.

**Pull request closed without merging**
