### PR TITLE
https://github.com/DominoKit/domino-ui/issues/350

### PR DESCRIPTION
**Pull request by HMIDeer**

### CODE REVIEW

**Comment by vegegoku** [comment]
We are taking this carefully because we are heavily using the select in one of our big application. so we need time to test this.

**Comment by vegegoku** [comment]
The functionally is added to the DropDownMenu but is not added to the Select class, please check this 
https://github.com/DominoKit/domino-ui/blob/master/domino-ui/src/main/java/org/dominokit/domino/ui/forms/AbstractSelect.java

the problem is that according to the implementation in this PR a dropdown can be searchable or creatable but not both, meanwhile, in the select we have logic that deals with the searchable flag.

in this implementation, we can set the select to be searchable, then set it to be creatable, but this will exclude the search function from the dropdown while the flag is still true.

I would prefer the implementation to make it possible to have both functions.

**Comment by HMIDeer** [comment]
Maybe I get that point wrong but the dropdown is still searchable if createable is set to true. The only thing which differs is the other element (Create "xxx") which is displayed in case the GUI user enters something which isn't in the list. So you want both elements to be displayed (No results matched "xxx") and (Create "xxx") in case searchable and creatable is true? For me thats a little bit weird for the GUI user

**Comment by vegegoku** [comment]
Based on the discussions we had on the issue we need to consider a few things here : 

- The behavior of default selecting the first element found.
- The ability to create new elements even if there are elements found.

My vision on this could be something like this

image

- If the Select is creatable we will add a button next to the search element.
- The create button will only be active when the search field has a value.
- The user can create and add a new element by click on the add button at any time or by press the tab to focus on the button then enter.
- Pressing enter on the search field will only select the first found option if exists.
- We do not assume we are adding strings, the select field can have a generic value which means we need to register some kind of addOptionHandler for which we pass the value from the search element and returns a SelectOption that if exists we append to the select. so It could return and optional. (also this can be used if the user wants to actually persist the new option somewhere)
- When we add a new option and after we append it we auto select that option.

**Pull request closed without merging**
