### PR TITLE
fix #316. DataTable scrollbar issues resolution

### LINKED ISSUE #316: Data table vertical scrollbar not visible
**Describe the bug**
When the datatable has a horizontal scrollbar, the vertical scrollbar is only visible when the horizontal scrollbar is scrolled to right.

**To Reproduce**
1. Go to https://demo.dominokit.org/datatable?theme=indigo
2. Open the data table samples
3. Scroll down to basic table - fixed example
4. Make sure your browser is small enough so that a horizontal scrollbar appears
5. You will no longer see the vertical scrollbar. It is only visible when scrolling to the right.

**Expected behavior**
Vertical scrollbar should be visible at all times

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79

### PR DESCRIPTION
**Pull request by salashnik**
+ added percentage column width support

ideas from:
* [scroll fix](https://stackoverflow.com/questions/14977864/fixed-header-table-with-horizontal-scrollbar-and-vertical-scrollbar-on) 
* [percentage](https://stackoverflow.com/questions/23989463/how-to-set-tbody-height-with-overflow-scroll)

### CODE REVIEW

**Comment by vegegoku** [comment]
domino-ui-issue-316
The fix from this PR is introducing another issue as in the gif above.

Ill keep this open for few days in case you want to update the PR and introduce a better fix.

**Comment by salashnik** [comment]
oops. please, dont close PR, i'm fix it

**Comment by salashnik** [comment]
@vegegoku, which browser You use? i check in chrome (86.0.4240.111) & FF (82.0.2) on linux, but all works as expected

Peek 2020-11-02 13-14

but i found another issue - body not change size when browser window resized.
I add new commit fixing this

in Your case, looks like scroll event not fired and this updateTableWidth not called :(
```
        tableElement.addEventListener("scroll", e -> updateTableWidth());
```

**Comment by vegegoku** [comment]
> @vegegoku, which browser You use? i check in chrome (86.0.4240.111) & FF (82.0.2) on linux, but all works as expected
> 
> Peek 2020-11-02 13-14
> 
> but i found another issue - body not change size when browser window resized.
> I add new commit fixing this
> 
> in Your case, looks like scroll event not fired and this updateTableWidth not called :(
> 
> ```
>         tableElement.addEventListener("scroll", e -> updateTableWidth());
> ```

I was using chrome Version 86.0.4240.111 (Official Build) (64-bit) on Linux/Ubuntu 20,04

**Comment by salashnik** [comment]
hi! i make some cleanup and retest all
i reproduce behavoiur from Your message only once< when i move listeners addition into another place and make without cleanup.
BUT, when i rebuild all with mvn clean ... all works again.

Can You try check again, with full cleanup when building?

**Comment by vegegoku** [comment]
> hi! i make some code cleanup and retest all
> i reproduce behavoiur from Your message only once< when i move listeners addition into another place and make without project clean.
> BUT, when i rebuild all with mvn clean ... all works again.
> 
> Can You try check again, with full cleanup when building?

Yup I was doing something wrong, I did a quick test later and found that it is working except for some special cases, later i will submit a recording trying to clearify those special cases.

**Comment by salashnik** [comment]
ok. ;-) but, please check latest version of the PR (i fix case with no-redraw when window resized)

**Pull request merged**
