### PR TITLE
let column header filter apply showOn and hideOn if them has been defined on columnConfig 

### PR DESCRIPTION
**Pull request by RaulPampliegaMayoral**
ColumnHeaderFilterPlugin its not applying the showOn and hideOn method

### CODE REVIEW

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral why do we have those other commits in this PR, i would merge this PR if had a cleaner commit.

**Comment by vegegoku** [comment]
@RaulPampliegaMayoral if you dont mind i would apply this fi myself and do some refactoring for this feature, we started to have some duplicate code.

**Comment by RaulPampliegaMayoral** [comment]
related issue: #180

**Comment by RaulPampliegaMayoral** [comment]
> 
> 
> @RaulPampliegaMayoral if you dont mind i would apply this fi myself and do some refactoring for this feature, we started to have some duplicate code.

I dont know how why these others commits are presents....i had to make a mistake. I also think that a refactor is needed with a more generic solution

**Comment by vegegoku** [comment]
fixed on

https://github.com/DominoKit/domino-ui/issues/180

https://github.com/DominoKit/domino-ui/commit/a0b224b539fe285b3f29c1cc8c507aeb8069bca1

@RaulPampliegaMayoral Thank you.

**Pull request closed without merging**
